issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:liatrio/.*"

permissions:
  contents: read
  packages: read

repositories:
  - liatrio-rego-policy-library
  - demo-gh-autogov-policy-library
  - autogov-helper
  - autogov-verify
  - k8s-platform-v3-ingress-auth-demo
  - liatrio-gh-autogov-workflows
  - hello-autogov
