issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:liatrio/tag-automated-governance-milestones:ref:refs/heads/main"

permissions:
  issues: write

repositories:
  - backstage-plugin-autogov
  - demo-autogov-hello-world-app
  - demo-gh-attest-autogov
  - demo-ootb-backstage
  - autogov-workflows
  - autogov-policy-library
  - autogov-helper
  - autogov-verify
  - tag-automated-governance-docs
  - tag-automated-governance-manifests
