# Allow order-service (and potentially other consumers) to read the contract
issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:liatrio/.*"

permissions:
  contents: read

repositories:
  - client-be-bff-integration-testing-poc-inventory-service
  - client-be-bff-integration-testing-poc-order-service
