issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:liatrio/tag-o11y-docs:.*
permissions:
  contents: read
  issues: write
  # projects: write
repositories:
  - Liatrio-Delivery-Methodology
  - tag-o11y-docs
  - tag-o11y-manifests
  - tag-o11y-honeycomb-infra
  - tag-o11y-github-actions
  - slack-telemetry-api
  - microservice-demo
