issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:liatrio/.*"

permissions:
  contents: read

repositories:
  - liatrio-rego-policy-library
  - demo-gh-autogov-policy-library
  - autogov-helper
  - autogov-verify
