issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:liatrio/.*:ref:refs/heads/main"

permissions:
  actions: read
  contents: write
  packages: write

repositories:
  - autogov
  - autogov-workflows
  - autogov-policy-library
